- hosts: localhost
  vars_prompt :
          - name : name
            prompt  : give me container name =
            private : no
  tasks:
  - copy:
          src : "/etc/yum.repos.d/docker.repo"
          dest: "/etc/yum.repos.d/docker-ce.repo"
  - command : "yum install docker-ce --nobest -y"

  - service:
          name: "docker"
          state: started
          enabled: yes
  - package :
          name : "python3"
          state: present
  - pip :
          name: "docker"        
  - file:
          state: directory
          path: "/myweb"
          
  - copy:
          dest: "/myweb/index.html"
          content: "my ansible container and its web page"

  - docker_container:
          name: "{{ name }}"
          image: "httpd"
          state: started
          exposed_ports:
                  - "80"
          ports:
                  - "2514:80"
          volumes:
                  - "/myweb:/var/www/html/"
    register : container_info   
  - blockinfile :
          dest : "/root/ip.txt"
          block : |
                  [docker]
                  {{ container_info['container']['NetworkSettings']['IPAddress']}} ansible_user=root ansible_ssh_pass=redhat ansible_connection=ssh
          marker : ""
- hosts : docker
  tasks:
  - package :
          name : "httpd"
  - service :
          name : "httpd"
          state  : restarted  
          
          







