- name: ec2 instances for configuring K8s cluster.
  hosts: localhost
  vars_files: 
       - secure.yml
  tasks: 
  - name: K8s Master Node.
    ec2:
      key_name: "key1515"
      instance_type: "t2.micro"
      image: "ami-0bcf5425cdc1d8a85"
      wait: yes
      count: 1
      vpc_subnet_id: "subnet-a57e77cd"
      region: "ap-south-1"
      state: present
      group_id: "sg-0ce366b398639e16c"
      assign_public_ip: yes
      instance_tags:
        Name: "Master"
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
    register: Master

  - name: K8s Slave Node.
    ec2:
      key_name: "key1515"
      instance_type: "t2.micro"
      image: "ami-0bcf5425cdc1d8a85"
      wait: yes
      count: 1
      vpc_subnet_id: "subnet-a57e77cd"
      region: "ap-south-1"
      state: present
      group_id: "sg-0ce366b398639e16c"
      assign_public_ip: yes
      instance_tags:
        Name: "Slave"
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}" 
    register: Slave                                                                                                                               

  - name: Update Inventory File
    blockinfile:
              dest: "/root/ip.txt"
              block: |
                        [Master]
                        {{ Master.instances[0].public_ip }} ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/etc/ansible/passw.pem
                          
                        [Slave]
                        {{ Slave.instances[0].public_ip }} ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/etc/ansible/passw.pem
